#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qs
    username: root
    password: Rootroot@1045


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  twilio:
    account_sid: AC8bd1ffe77b6d18ad70e465ea67a071f6
    auth_token: 11944b6e6dcbdf0e6c6ce9e646761d93
    service_id: VA6300a3f7095e7e6f594292973a86238b